# Generated by Django 5.1.6 on 2025-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('Processor', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('colours', models.CharField(max_length=50)),
                ('batteryCapacity', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('rearCamera', models.CharField(max_length=50)),
                ('frontCamera', models.CharField(max_length=50)),
            ],
        ),
    ]
