# Generated by Django 5.1.6 on 2025-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_phones',
            name='ram',
            field=models.CharField(default=8, max_length=50),
        ),
    ]
