# Generated by Django 5.1.7 on 2025-04-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_smart_phones_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('Processor', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=50)),
                ('ram', models.CharField(default=8, max_length=50)),
                ('Memory_Storage', models.CharField(max_length=50)),
                ('Resolution', models.CharField(max_length=50)),
                ('batteryCapacity', models.CharField(max_length=50)),
                ('Features', models.CharField(max_length=100)),
                ('amazon', models.CharField(max_length=50)),
                ('flipkart', models.CharField(max_length=50)),
                ('Reliance', models.CharField(max_length=50)),
                ('ebay', models.CharField(max_length=50)),
            ],
        ),
    ]
