# Generated by Django 5.1.6 on 2025-04-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_laptops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptops',
            old_name='ebay',
            new_name='Brand_site',
        ),
        migrations.AddField(
            model_name='smart_phones',
            name='Brand_site',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smart_phones',
            name='Reliance',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smart_phones',
            name='amazon',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smart_phones',
            name='flipkart',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
