# Generated by Django 5.1.6 on 2025-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_rename_ebay_laptops_brand_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('Processor', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('Colors', models.CharField(max_length=50)),
                ('Sensors', models.CharField(max_length=100)),
                ('Resolution', models.CharField(max_length=50)),
                ('batteryCapacity', models.CharField(max_length=50)),
                ('Features', models.CharField(max_length=100)),
                ('amazon', models.CharField(max_length=50)),
                ('flipkart', models.CharField(max_length=50)),
                ('Reliance', models.CharField(max_length=50)),
                ('Brand_site', models.CharField(max_length=50)),
            ],
        ),
    ]
